# Generated by Django 3.2.7 on 2021-10-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manatal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=36),
        ),
    ]
